version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
    networks:
      - app
  
  redis: 
    container_name: lc-api-redis
    image: 'redis'
    ports:
      - "6379:6379"
    networks:
      - app
      

networks:
  app: